language: android

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
 - ./gradlew clean assemble

after_success:
 - ./gradlew bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false

notifications:
  email: false