language: android

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-28
    - extra-android-m2repository
    - platform-tools
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
 - ./gradlew clean assemble

after_success:
 - ./gradlew bintrayUpload -PdryRun=false

notifications:
  email: false